# Generated by Django 4.2.30 on 2026-06-06 07:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('batches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='trainers',
            field=models.ManyToManyField(blank=True, related_name='batches', to=settings.AUTH_USER_MODEL),
        ),
    ]
