# Generated by Django 4.2.30 on 2026-06-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0003_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
