# Generated by Django 4.2.23 on 2026-06-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0004_batch_latitude_batch_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='status',
            field=models.CharField(choices=[('inactive', 'Inactive'), ('active', 'Active'), ('completed', 'Completed')], default='active', max_length=15),
        ),
    ]
