# Generated by Django 4.2.30 on 2026-06-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0006_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='districts',
            field=models.TextField(blank=True, null=True),
        ),
    ]
