# Generated by Django 4.2.30 on 2026-06-10 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0007_zone_districts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Zone',
        ),
    ]
