# Generated by Django 4.2.30 on 2026-06-10 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regional_office', '0002_division_alter_regionaloffice_division'),
        ('batches', '0008_delete_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='regional_office.division'),
        ),
        migrations.AddField(
            model_name='batch',
            name='program',
            field=models.CharField(choices=[('dabi', 'Dabi'), ('progoti', 'Progoti')], default='dabi', max_length=20),
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
