# Generated by Django 4.2.30 on 2026-06-12 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0009_batch_division_batch_program_alter_batch_batch_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_type', models.CharField(choices=[('basic', 'Basic'), ('refresher_1', 'Refresher 1'), ('refresher_2', 'Refresher 2')], default='basic', max_length=20)),
                ('format', models.CharField(blank=True, choices=[('face_to_face', 'Face-to-Face'), ('online', 'Online')], max_length=20, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='batches.batch')),
            ],
            options={
                'ordering': ['stage_type'],
                'unique_together': {('batch', 'stage_type')},
            },
        ),
    ]
