# Generated by Django 4.2.30 on 2026-06-12 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regional_office', '0002_division_alter_regionaloffice_division'),
        ('batches', '0011_attendance_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='regional_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='regional_office.regionaloffice'),
        ),
    ]
