# Generated statically from bdapis.com
LOCATIONS = [
    "Abhaynagar (Jashore)",
    "Adamdighi (Bogura)",
    "Aditmari (Lalmonirhat)",
    "Agailjhara (Barishal)",
    "Ajmiriganj (Habiganj)",
    "Akhaura (Brahmanbaria)",
    "Akkelpur (Joypurhat)",
    "Alamdanga (Chuadanga)",
    "Alfadanga (Faridpur)",
    "Ali Kadam (Bandarban)",
    "Amtali (Barguna)",
    "Anwara (Chattogram)",
    "Araihazar (Narayanganj)",
    "Ashuganj (Brahmanbaria)",
    "Assasuni (Satkhira)",
    "Atgharia (Pabna)",
    "Atpara (Netrokona)",
    "Atrai (Naogaon)",
    "Atwari (Panchagarh)",
    "Austagram (Kishoreganj)",
    "Babuganj (Barishal)",
    "Badalgachhi (Naogaon)",
    "Badarganj (Rangpur)",
    "Bagaichhari (Rangamati)",
    "Bagatipara (Natore)",
    "Bagerhat",
    "Bagerhat Sadar (Bagerhat)",
    "Bagha (Rajshahi)",
    "Bagherpara (Jashore)",
    "Bagmara (Rajshahi)",
    "Bahubal (Habiganj)",
    "Bajitpur (Kishoreganj)",
    "Bakerganj (Barishal)",
    "Baksiganj (Jamalpur)",
    "Balaganj (Sylhet)",
    "Baliadangi (Thakurgaon)",
    "Baliakandi (Rajbari)",
    "Bamna (Barguna)",
    "Banaripara (Barishal)",
    "Bancharampur (Brahmanbaria)",
    "Bandar (Narayanganj)",
    "Bandarban",
    "Bandarban Sadar (Bandarban)",
    "Baniyachong (Habiganj)",
    "Banshkhali (Chattogram)",
    "Baraigram (Natore)",
    "Barguna",
    "Barguna Sadar (Barguna)",
    "Barhatta (Netrokona)",
    "Barisal Sadar (Barishal)",
    "Barishal",
    "Barkal (Rangamati)",
    "Barlekha (Moulvibazar)",
    "Barura (Cumilla)",
    "Basail (Tangail)",
    "Batiaghata (Khulna)",
    "Bauphal (Patuakhali)",
    "Beanibazar (Sylhet)",
    "Begumganj (Noakhali)",
    "Belabo (Narsingdi)",
    "Belaichhari (Rangamati)",
    "Belkuchi (Sirajganj)",
    "Bera (Pabna)",
    "Betagi (Barguna)",
    "Bhairab (Kishoreganj)",
    "Bhaluka (Mymensingh)",
    "Bhandaria (Pirojpur)",
    "Bhanga (Faridpur)",
    "Bhangura (Pabna)",
    "Bhedarganj (Shariatpur)",
    "Bheramara (Kushtia)",
    "Bhola",
    "Bhola Sadar (Bhola)",
    "Bholahat (Chapai Nawabganj)",
    "Bhuapur (Tangail)",
    "Bhurungamari (Kurigram)",
    "Bijoynagar (Brahmanbaria)",
    "Biral (Dinajpur)",
    "Birampur (Dinajpur)",
    "Birganj (Dinajpur)",
    "Bishwamvarpur (Sunamganj)",
    "Bishwanath (Sylhet)",
    "Boalkhali (Chattogram)",
    "Boalmari (Faridpur)",
    "Bochaganj (Dinajpur)",
    "Boda (Panchagarh)",
    "Bogura",
    "Bogura Sadar (Bogura)",
    "Brahmanbaria",
    "Brahmanbaria Sadar (Brahmanbaria)",
    "Brahmanpara (Cumilla)",
    "Burhanuddin (Bhola)",
    "Burichang (Cumilla)",
    "Chakaria (Cox's Bazar)",
    "Chandanaish (Chattogram)",
    "Chandina (Cumilla)",
    "Chandpur",
    "Chandpur Sadar (Chandpur)",
    "Chapai Nawabganj",
    "Chapai Nawabganj Sadar (Chapai Nawabganj)",
    "Char Fasson (Bhola)",
    "Char Rajibpur (Kurigram)",
    "Charbhadrasan (Faridpur)",
    "Charghat (Rajshahi)",
    "Chatkhil (Noakhali)",
    "Chatmohar (Pabna)",
    "Chattogram",
    "Chauddagram (Cumilla)",
    "Chaugachha (Jashore)",
    "Chauhali (Sirajganj)",
    "Chhagalnaiya (Feni)",
    "Chhatak (Sunamganj)",
    "Chilmari (Kurigram)",
    "Chirirbandar (Dinajpur)",
    "Chitalmari (Bagerhat)",
    "Chuadanga",
    "Chuadanga Sadar (Chuadanga)",
    "Chunarughat (Habiganj)",
    "Companiganj (Noakhali)",
    "Companigonj (Sylhet)",
    "Cox's Bazar",
    "Cox's Bazar Sadar (Cox's Bazar)",
    "Cumilla",
    "Cumilla Adarsha Sadar (Cumilla)",
    "Cumilla Sadar Dakshin (Cumilla)",
    "Dacope (Khulna)",
    "Daganbhuiyan (Feni)",
    "Dakshin Sunamganj (Sunamganj)",
    "Dakshin Surma (Sylhet)",
    "Damudya (Shariatpur)",
    "Damurhuda (Chuadanga)",
    "Dashmina (Patuakhali)",
    "Daudkandi (Cumilla)",
    "Daulatkhan (Bhola)",
    "Daulatpur (Kushtia)",
    "Daulatpur (Manikganj)",
    "Debhata (Satkhira)",
    "Debidwar (Cumilla)",
    "Debiganj (Panchagarh)",
    "Delduar (Tangail)",
    "Derai (Sunamganj)",
    "Dewanganj (Jamalpur)",
    "Dhaka",
    "Dhamoirhat (Naogaon)",
    "Dhamrai (Dhaka)",
    "Dhanbari (Tangail)",
    "Dharamapasha (Sunamganj)",
    "Dhobaura (Mymensingh)",
    "Dhunat (Bogura)",
    "Dhupchanchia (Bogura)",
    "Dighalia (Khulna)",
    "Dighinala (Khagrachari)",
    "Dimla (Nilphamari)",
    "Dinajpur",
    "Dinajpur Sadar (Dinajpur)",
    "Dohar (Dhaka)",
    "Domar (Nilphamari)",
    "Dowarabazar (Sunamganj)",
    "Dumki (Patuakhali)",
    "Dumuria (Khulna)",
    "Durgapur (Netrokona)",
    "Durgapur (Rajshahi)",
    "Fakirhat (Bagerhat)",
    "Faridganj (Chandpur)",
    "Faridpur",
    "Faridpur (Pabna)",
    "Faridpur Sadar (Faridpur)",
    "Fatikchhari (Chattogram)",
    "Fenchuganj (Sylhet)",
    "Feni",
    "Feni Sadar (Feni)",
    "Fulbaria (Mymensingh)",
    "Fulgazi (Feni)",
    "Gabtali (Bogura)",
    "Gafargaon (Mymensingh)",
    "Gaibandha",
    "Gaibandha Sadar (Gaibandha)",
    "Galachipa (Patuakhali)",
    "Gangachhara (Rangpur)",
    "Gangni (Meherpur)",
    "Gauripur (Mymensingh)",
    "Gaurnadi (Barishal)",
    "Gazaria (Munshiganj)",
    "Gazipur",
    "Gazipur Sadar (Gazipur)",
    "Ghatail (Tangail)",
    "Ghior (Manikganj)",
    "Ghoraghat (Dinajpur)",
    "Goalandaghat (Rajbari)",
    "Gobindaganj (Gaibandha)",
    "Godagari (Rajshahi)",
    "Golapganj (Sylhet)",
    "Gomastapur (Chapai Nawabganj)",
    "Gopalganj",
    "Gopalganj Sadar (Gopalganj)",
    "Gopalpur (Tangail)",
    "Gosairhat (Shariatpur)",
    "Gowainghat (Sylhet)",
    "Gurudaspur (Natore)",
    "Habiganj",
    "Habiganj Sadar (Habiganj)",
    "Haimchar (Chandpur)",
    "Hakimpur (Dinajpur)",
    "Haluaghat (Mymensingh)",
    "Harinakunda (Jhenaidah)",
    "Haripur (Thakurgaon)",
    "Harirampur (Manikganj)",
    "Hathazari (Chattogram)",
    "Hatibandha (Lalmonirhat)",
    "Hatiya (Noakhali)",
    "Haziganj (Chandpur)",
    "Hizla (Barishal)",
    "Homna (Cumilla)",
    "Hossainpur (Kishoreganj)",
    "Indurkani (Pirojpur)",
    "Ishwardi (Pabna)",
    "Ishwarganj (Mymensingh)",
    "Islampur (Jamalpur)",
    "Itna (Kishoreganj)",
    "Jagannathpur (Sunamganj)",
    "Jaintiapur (Sylhet)",
    "Jaldhaka (Nilphamari)",
    "Jamalganj (Sunamganj)",
    "Jamalpur",
    "Jamalpur Sadar (Jamalpur)",
    "Jashore",
    "Jashore Sadar (Jashore)",
    "Jhalokati",
    "Jhalokati Sadar (Jhalokati)",
    "Jhenaidah",
    "Jhenaidah Sadar (Jhenaidah)",
    "Jhenaigati (Sherpur)",
    "Jhikargachha (Jashore)",
    "Jibannagar (Chuadanga)",
    "Joypurhat",
    "Joypurhat Sadar (Joypurhat)",
    "Juraichhari (Rangamati)",
    "Juri (Moulvibazar)",
    "Kabirhat (Noakhali)",
    "Kachua (Bagerhat)",
    "Kachua (Chandpur)",
    "Kahaloo (Bogura)",
    "Kaharole (Dinajpur)",
    "Kalai (Joypurhat)",
    "Kalapara (Patuakhali)",
    "Kalaroa (Satkhira)",
    "Kalia (Narail)",
    "Kaliakair (Gazipur)",
    "Kaliganj (Gazipur)",
    "Kaliganj (Jhenaidah)",
    "Kaliganj (Lalmonirhat)",
    "Kaliganj (Satkhira)",
    "Kalihati (Tangail)",
    "Kalkini (Madaripur)",
    "Kalmakanda (Netrokona)",
    "Kalukhali (Rajbari)",
    "Kamalganj (Moulvibazar)",
    "Kamalnagar (Lakshmipur)",
    "Kamarkhanda (Sirajganj)",
    "Kanaighat (Sylhet)",
    "Kapasia (Gazipur)",
    "Kaptai (Rangamati)",
    "Karimganj (Kishoreganj)",
    "Karnaphuli (Chattogram)",
    "Kasba (Brahmanbaria)",
    "Kashiani (Gopalganj)",
    "Kathalia (Jhalokati)",
    "Katiadi (Kishoreganj)",
    "Kaunia (Rangpur)",
    "Kawkhali (Pirojpur)",
    "Kawkhali (Rangamati)",
    "Kazipur (Sirajganj)",
    "Kendua (Netrokona)",
    "Keraniganj (Dhaka)",
    "Keshabpur (Jashore)",
    "Khagrachari",
    "Khagrachhari Sadar (Khagrachari)",
    "Khaliajuri (Netrokona)",
    "Khansama (Dinajpur)",
    "Khetlal (Joypurhat)",
    "Khoksa (Kushtia)",
    "Khulna",
    "Kishoreganj",
    "Kishoreganj (Nilphamari)",
    "Kishoreganj Sadar (Kishoreganj)",
    "Kotalipara (Gopalganj)",
    "Kotchandpur (Jhenaidah)",
    "Koyra (Khulna)",
    "Kulaura (Moulvibazar)",
    "Kuliarchar (Kishoreganj)",
    "Kumarkhali (Kushtia)",
    "Kurigram",
    "Kurigram Sadar (Kurigram)",
    "Kushtia",
    "Kushtia Sadar (Kushtia)",
    "Kutubdia (Cox's Bazar)",
    "Lakhai (Habiganj)",
    "Laksam (Cumilla)",
    "Lakshmichhari (Khagrachari)",
    "Lakshmipur",
    "Lakshmipur Sadar (Lakshmipur)",
    "Lalmai (Cumilla)",
    "Lalmohan (Bhola)",
    "Lalmonirhat",
    "Lalmonirhat Sadar (Lalmonirhat)",
    "Lalpur (Natore)",
    "Lama (Bandarban)",
    "Langadu (Rangamati)",
    "Lohagara (Chattogram)",
    "Lohagara (Narail)",
    "Lohajang (Munshiganj)",
    "Madan (Netrokona)",
    "Madarganj (Jamalpur)",
    "Madaripur",
    "Madaripur Sadar (Madaripur)",
    "Madhabpur (Habiganj)",
    "Madhukhali (Faridpur)",
    "Madhupur (Tangail)",
    "Magura",
    "Magura Sadar (Magura)",
    "Mahalchhari (Khagrachari)",
    "Maheshkhali (Cox's Bazar)",
    "Maheshpur (Jhenaidah)",
    "Manda (Naogaon)",
    "Manikchhari (Khagrachari)",
    "Manikganj",
    "Manikgonj Sadar (Manikganj)",
    "Manirampur (Jashore)",
    "Manpura (Bhola)",
    "Mathbaria (Pirojpur)",
    "Matiranga (Khagrachari)",
    "Matlab Dakshin (Chandpur)",
    "Matlab Uttar (Chandpur)",
    "Meghna (Cumilla)",
    "Mehendiganj (Barishal)",
    "Meherpur",
    "Meherpur Sadar (Meherpur)",
    "Melandaha (Jamalpur)",
    "Mirpur (Kushtia)",
    "Mirsharai (Chattogram)",
    "Mirzaganj (Patuakhali)",
    "Mirzapur (Tangail)",
    "Mithamain (Kishoreganj)",
    "Mithapukur (Rangpur)",
    "Mohadevpur (Naogaon)",
    "Mohammadpur (Magura)",
    "Mohanganj (Netrokona)",
    "Mohanpur (Rajshahi)",
    "Mollahat (Bagerhat)",
    "Mongla (Bagerhat)",
    "Monohardi (Narsingdi)",
    "Monohargonj (Cumilla)",
    "Morrelganj (Bagerhat)",
    "Moulvibazar",
    "Moulvibazar Sadar (Moulvibazar)",
    "Mujibnagar (Meherpur)",
    "Muksudpur (Gopalganj)",
    "Muktagachha (Mymensingh)",
    "Muladi (Barishal)",
    "Munshiganj",
    "Munshiganj Sadar (Munshiganj)",
    "Muradnagar (Cumilla)",
    "Mymensingh",
    "Mymensingh Sadar (Mymensingh)",
    "Nabiganj (Habiganj)",
    "Nabinagar (Brahmanbaria)",
    "Nachole (Chapai Nawabganj)",
    "Nagarkanda (Faridpur)",
    "Nagarpur (Tangail)",
    "Nageshwari (Kurigram)",
    "Naikhongchhari (Bandarban)",
    "Nakla (Sherpur)",
    "Nalchhiti (Jhalokati)",
    "Naldanga (Natore)",
    "Nalitabari (Sherpur)",
    "Nandail (Mymensingh)",
    "Nandigram (Bogura)",
    "Nangalkot (Cumilla)",
    "Naniyachar (Rangamati)",
    "Naogaon",
    "Naogaon Sadar (Naogaon)",
    "Narail",
    "Narail Sadar (Narail)",
    "Narayanganj",
    "Narayanganj Sadar (Narayanganj)",
    "Naria (Shariatpur)",
    "Narsingdi",
    "Narsingdi Sadar (Narsingdi)",
    "Nasirnagar (Brahmanbaria)",
    "Natore",
    "Natore Sadar (Natore)",
    "Nawabganj (Dhaka)",
    "Nawabganj (Dinajpur)",
    "Nazirpur (Pirojpur)",
    "Nesarabad (Swarupkati) (Pirojpur)",
    "Netrokona",
    "Netrokona Sadar (Netrokona)",
    "Niamatpur (Naogaon)",
    "Nikli (Kishoreganj)",
    "Nilphamari",
    "Nilphamari Sadar (Nilphamari)",
    "Noakhali",
    "Noakhali Sadar (Noakhali)",
    "Osmani Nagar (Sylhet)",
    "Paba (Rajshahi)",
    "Pabna",
    "Pabna Sadar (Pabna)",
    "Paikgachha (Khulna)",
    "Pakundia (Kishoreganj)",
    "Palash (Narsingdi)",
    "Palashbari (Gaibandha)",
    "Panchagarh",
    "Panchagarh Sadar (Panchagarh)",
    "Panchbibi (Joypurhat)",
    "Panchhari (Khagrachari)",
    "Pangsha (Rajbari)",
    "Parbatipur (Dinajpur)",
    "Parshuram (Feni)",
    "Patgram (Lalmonirhat)",
    "Patharghata (Barguna)",
    "Patiya (Chattogram)",
    "Patnitala (Naogaon)",
    "Patuakhali",
    "Patuakhali Sadar (Patuakhali)",
    "Pekua (Cox's Bazar)",
    "Phulbari (Dinajpur)",
    "Phulbari (Kurigram)",
    "Phulchhari (Gaibandha)",
    "Phulpur (Mymensingh)",
    "Phultala (Khulna)",
    "Pirgachha (Rangpur)",
    "Pirganj (Rangpur)",
    "Pirganj (Thakurgaon)",
    "Pirojpur",
    "Pirojpur Sadar (Pirojpur)",
    "Porsha (Naogaon)",
    "Purbadhala (Netrokona)",
    "Puthia (Rajshahi)",
    "Raiganj (Sirajganj)",
    "Raipur (Lakshmipur)",
    "Raipura (Narsingdi)",
    "Rajapur (Jhalokati)",
    "Rajarhat (Kurigram)",
    "Rajasthali (Rangamati)",
    "Rajbari",
    "Rajbari Sadar (Rajbari)",
    "Rajnagar (Moulvibazar)",
    "Rajoir (Madaripur)",
    "Rajshahi",
    "Ramganj (Lakshmipur)",
    "Ramgarh (Khagrachari)",
    "Ramgati (Lakshmipur)",
    "Rampal (Bagerhat)",
    "Ramu (Cox's Bazar)",
    "Rangabali (Patuakhali)",
    "Rangamati",
    "Rangamati Sadar (Rangamati)",
    "Rangpur",
    "Rangpur Sadar (Rangpur)",
    "Rangunia (Chattogram)",
    "Raninagar (Naogaon)",
    "Ranisankail (Thakurgaon)",
    "Raomari (Kurigram)",
    "Raozan (Chattogram)",
    "Rowangchhari (Bandarban)",
    "Ruma (Bandarban)",
    "Rupganj (Narayanganj)",
    "Rupsha (Khulna)",
    "Sadarpur (Faridpur)",
    "Sadullapur (Gaibandha)",
    "Saidpur (Nilphamari)",
    "Sakhipur (Tangail)",
    "Saltha (Faridpur)",
    "Sandwip (Chattogram)",
    "Santhia (Pabna)",
    "Sapahar (Naogaon)",
    "Sarail (Brahmanbaria)",
    "Sarankhola (Bagerhat)",
    "Sariakandi (Bogura)",
    "Sarishabari (Jamalpur)",
    "Satkania (Chattogram)",
    "Satkhira",
    "Satkhira Sadar (Satkhira)",
    "Saturia (Manikganj)",
    "Savar (Dhaka)",
    "Sayestaganj (Habiganj)",
    "Senbagh (Noakhali)",
    "Shahjadpur (Sirajganj)",
    "Shahrasti (Chandpur)",
    "Shailkupa (Jhenaidah)",
    "Shajahanpur (Bogura)",
    "Shalikha (Magura)",
    "Shariatpur",
    "Shariatpur Sadar (Shariatpur)",
    "Sharsha (Jashore)",
    "Sherpur",
    "Sherpur (Bogura)",
    "Sherpur Sadar (Sherpur)",
    "Shibchar (Madaripur)",
    "Shibganj (Bogura)",
    "Shibganj (Chapai Nawabganj)",
    "Shibpur (Narsingdi)",
    "Shivalaya (Manikganj)",
    "Shyamnagar (Satkhira)",
    "Singair (Manikganj)",
    "Singra (Natore)",
    "Sirajdikhan (Munshiganj)",
    "Sirajganj",
    "Sirajganj Sadar (Sirajganj)",
    "Sitakunda (Chattogram)",
    "Sonagazi (Feni)",
    "Sonaimuri (Noakhali)",
    "Sonargaon (Narayanganj)",
    "Sonatola (Bogura)",
    "Sreebardi (Sherpur)",
    "Sreemangal (Moulvibazar)",
    "Sreenagar (Munshiganj)",
    "Sreepur (Gazipur)",
    "Sreepur (Magura)",
    "Subarnachar (Noakhali)",
    "Sughatta (Gaibandha)",
    "Sujanagar (Pabna)",
    "Sullah (Sunamganj)",
    "Sunamganj",
    "Sunamganj Sadar (Sunamganj)",
    "Sundarganj (Gaibandha)",
    "Sylhet",
    "Sylhet Sadar (Sylhet)",
    "Tahirpur (Sunamganj)",
    "Tala (Satkhira)",
    "Taltali (Barguna)",
    "Tangail",
    "Tangail Sadar (Tangail)",
    "Tanore (Rajshahi)",
    "Tara Khanda (Mymensingh)",
    "Taraganj (Rangpur)",
    "Tarail (Kishoreganj)",
    "Tarash (Sirajganj)",
    "Tazumuddin (Bhola)",
    "Teknaf (Cox's Bazar)",
    "Terokhada (Khulna)",
    "Tetulia (Panchagarh)",
    "Thakurgaon",
    "Thakurgaon Sadar (Thakurgaon)",
    "Thanchi (Bandarban)",
    "Titas (Cumilla)",
    "Tongibari (Munshiganj)",
    "Trishal (Mymensingh)",
    "Tungipara (Gopalganj)",
    "Ukhia (Cox's Bazar)",
    "Ulipur (Kurigram)",
    "Ullahpara (Sirajganj)",
    "Wazirpur (Barishal)",
    "Zajira (Shariatpur)",
    "Zakiganj (Sylhet)"
]
