# Generated by Django 4.2.30 on 2026-06-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('training_center', 'Training Center'), ('hotel', 'Hotel')], default='training_center', max_length=50)),
                ('room_type', models.CharField(choices=[('suite', 'Suite'), ('single', 'Single Accommodation'), ('twin_share', 'Twin Share')], default='single', max_length=50)),
                ('room_unit_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('classroom_type', models.CharField(choices=[('conference_room', 'Conference Room'), ('std_classroom', 'Standard Classroom')], default='std_classroom', max_length=50)),
                ('classroom_unit_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('has_wifi', models.BooleanField(default=False)),
                ('has_projector', models.BooleanField(default=False)),
                ('has_whiteboard', models.BooleanField(default=False)),
                ('has_dining', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Accommodation',
                'verbose_name_plural': 'Accommodations',
            },
        ),
        migrations.CreateModel(
            name='LogisticsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('stationary', 'Stationary'), ('it', 'IT Logistics')], default='stationary', max_length=50)),
                ('quantity', models.IntegerField(default=0)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Logistics Item',
                'verbose_name_plural': 'Logistics Items',
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('bus', 'Bus'), ('microbus', 'Microbus'), ('car', 'Car')], default='bus', max_length=50)),
                ('capacity', models.IntegerField(default=4)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Transport',
                'verbose_name_plural': 'Transports',
            },
        ),
    ]
