# Generated by Django 4.2.30 on 2026-06-06 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0005_batch_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticsRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField(blank=True, null=True)),
                ('check_out_date', models.DateField(blank=True, null=True)),
                ('num_trainers', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accommodation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.accommodation')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logistics_requests', to='batches.batch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Logistics Request',
                'verbose_name_plural': 'Logistics Requests',
            },
        ),
        migrations.CreateModel(
            name='LogisticsRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.logisticsitem')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_items', to='logistics.logisticsrequest')),
            ],
            options={
                'verbose_name': 'Logistics Request Item',
                'verbose_name_plural': 'Logistics Request Items',
                'unique_together': {('request', 'item')},
            },
        ),
    ]
