# Generated by Django 4.2.30 on 2026-06-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_logisticsrequest_logisticsrequestitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
