# Generated by Django 4.2.30 on 2026-06-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_accommodation_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='logisticsrequest',
            name='accommodation_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='logisticsrequest',
            name='is_opened',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='logisticsrequest',
            name='it_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='logisticsrequest',
            name='stationary_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
