# Generated by Django 4.2.30 on 2026-06-10 11:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionalOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('division', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('regional_managers', models.ManyToManyField(blank=True, related_name='regional_offices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
