# Generated by Django 4.2.30 on 2026-06-12 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regional_office', '0002_division_alter_regionaloffice_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionaloffice',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='regionaloffice',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
