# Generated by Django 4.2.30 on 2026-06-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('program_supervisor', 'Program Supervisor'), ('batch_manager', 'Batch Manager'), ('master_trainer', 'Master Trainer'), ('trainer', 'Trainer'), ('logistic_manager', 'Logistic Manager'), ('regional_manager', 'RM - Regional Manager')], default='trainer', max_length=30),
        ),
    ]
